sonar.projectKey=markoboger_tritongraph
sonar.projectName=tritongraph
sonar.organization=markoboger

# Sources and tests
sonar.sources=editor/src
sonar.tests=editor/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.bench.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.bench.ts

# TypeScript / JavaScript
sonar.javascript.lcov.reportPaths=editor/coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8
