services:
  app:
    build: ./app
    image: docker-examples-04-app:local
    command: ["sleep", "infinity"]
    ports:
      - "18082:8080"
    volumes:
      - app-cache:/tmp/cache
    networks: [app-net]
    depends_on:
      - db
  db:
    build: ./db
    image: docker-examples-04-db:local
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - db-data:/var/lib/postgresql/data
    networks: [app-net]

volumes:
  db-data:
  app-cache:

networks:
  app-net:
    driver: bridge
