services:
  api:
    build: ./api
    image: docker-examples-03-api:local
    command: ["sleep", "infinity"]
    networks: [internal]
  worker:
    build: ./worker
    image: docker-examples-03-worker:local
    command: ["sleep", "infinity"]
    depends_on:
      - api
    networks: [internal]

networks:
  internal:
    driver: bridge
