export { SBT_GRAMMAR_REFERENCE_URLS } from './sbtGrammar.js'
export { parseBuildSbt, stripScalaComments, type SbtSubproject } from './parseBuildSbt.js'
export { sbtProjectsToIlograph } from './buildIlograph.js'
export { stringifyIlographYaml } from './yamlOut.js'
export type { IlographDocument, IlographPerspective, IlographRelation, IlographResource } from './ilographTypes.js'
